name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Lancer les tests
      - name: Run tests
        run: npm test

      # Linter (si ESLint est configuré)
      - name: Run linter
        run: npm run lint
        continue-on-error: true # Ne bloque pas si le linter échoue

      # Construire le projet (si applicable)
      - name: Build project
        run: npm run build
        if: success()

      # Upload des logs (optionnel)
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/



